---
- hosts: localhost

  tasks:

    - name: credential retrieval basic
      cyberark_credential:
        api_base_url: "http://10.0.1.12"
        app_id: "Ansible"
        query: "Safe=Ansible-Demo;UserName=admin"
      register: "{{ result }}"
      no_log: false


    - name: Debug message
      debug: 
        var: "{{ result }}"
