---
  - hosts: localhost
    connection: local
    
    tasks:
      - name: Exchange API key for access token
        uri:
          url: "{{ ansible_env.CONJUR_APPLIANCE_URL }}/authn/cyberark/host%2Fansible-tower%2Fnodes%2Ftower2/authenticate"
          method: POST
          timeout: 10
          validate_certs: no
          headers:
            Content-Type: "text/plain"
          body: "{{ ansible_env.CONJUR_AUTHN_API_KEY }}"
          return_content: yes
          status_code: 200
          body_format: json
        register: token_json
      - set_fact: token="{{ token_json.content | b64encode | replace('\r\n', '') }}"
      - debug:
          msg: "{{ token }}"

      - name: Use token to retrieve secret
        uri:
          url: "{{ansible_env.CONJUR_APPLIANCE_URL}}/secrets/cyberark/ansible-tower%2Fnodes%2Fdb-password?version=1"
          method: GET
          timeout: 10
          validate_certs: no
          headers:
            Authorization: Token token="{{ token }}"
            Content-Type: "application/json"
          return_content: yes
          status_code: 200      
        register: variable_value
      - debug:
          msg: "{{ variable_value.content }}"
