---
- hosts: localhost

  tasks:

    - name: Credential Retrieval - Whitelisted IP Only
      cyberark_credential:
        api_base_url: "http://10.0.1.12"
        app_id: "Ansible"
        query: "Safe=Ansible-Test;UserName=admin"
        validate_certs: false
      register: result
      no_log: true


    - name: JSON Response from AIM CCP
      debug: 
        msg: "{{ result }}"
