- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: cyberark-bizdev.password_lookup_plugin

  vars:
    - su_user: '{{ lookup("cyberarkpassword", { "appid": "Ansible_Demo", "Query": "Safe=Ansible Demo;Folder=Root;Object=ansible-demo_ansible-controller_root;Username=root", "output": "PassProps.Username" }) }}'
    - su_pass: '{{ lookup("cyberarkpassword", { "appid": "Ansible_Demo", "Query": "Safe=Ansible Demo;Folder=Root;Object=ansible-demo_ansible-controller_root;Username=root", "output": "Password" }) }}'
  
  tasks:
    - name: Output Superuser Username Securely Retrieved from CyberArk Conjur
      debug:
        var: su_user

    - name: Output Superuser Password Securely Retrieved from CyberArk Conjur
      debug:
        var: su_pass