- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Output Superuser Username Securely Retrieved from CyberArk EPV
      debug:
        msg: '{{ item }}'
      with_cyberarkpassword:
        appid: 'Ansible-Demo'
        query: 'safe=Ansible-Demo;folder=Root;object=ansible-demo_ansible-controller_root'
        output: 'PassProps.UserName'

    - name: Output Superuser Password Securely Retrieved from CyberArk EPV
      debug:
        msg: '{{ item }}'
      with_cyberarkpassword:
        appid: 'Ansible-Demo'
        query: 'safe=Ansible-Demo;folder=Root;object=ansible-demo_ansible-controller_root'
        output: 'Password'