---
- hosts: localhost

  tasks:

    - name: Credential Retrieval - Whitelisted IP & Client Certificate Auth
      cyberark_credential:
        api_base_url: "http://10.0.1.12"
        client_cert: "{{ ansible_env.CLIENT_CERTIFICATE }}"
        client_key: "{{ ansible_env.CLIENT_KEY }}"
        app_id: "Ansible"
        query: "Safe=Ansible-Test;UserName=admin"
        validate_certs: false
      register: result
      delegate_to: localhost
      no_log: false


    - name: JSON Response from AIM CCP
      debug: 
        msg: "{{ result }}"
